name: auctioneer-env

# Channels: prefer conda-forge for everything; defaults left as a fallback.
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - pyyaml
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
